### ISSUE TITLE
BlackBerry Leap Support 

### ISSUE THREAD

**Issue by user-devisuite** [marcossit-dev/devicesuite#13]
Processor name, GPU, GPU clock rate doesn't show up.

**Comment by marcossit-dev** [comment]
Hello please send to me mail (marcossit@zonablackberry.com) screenshots the problem and send Model, os

Thanks

PS ComingSoon Support for BlackBerry Leap Thanks

**Comment by marcossit-dev** [comment]
Leap Support in V5.1.30.1 Thanks
